on3iro/aeons-end-randomizer

- package.json
- src/components/Settings.jsx
- src/components/Supply.jsx
- src/components/helpers.js
- src/components/marketSetups.js
> Add market setup selection

- src/components/App/DrawerMenu.jsx
- src/components/App/appStyles.js
> [Task] Style app information and github link

- src/components/pages/TurnOrder/hooks.js
- src/components/pages/TurnOrder/index.jsx
Closes: #34, #32
* Also reverses turn order discard
> [FEATURE] Persist turn order game state + refactoring

- src/components/StyledExpansionPanel.jsx
- src/components/StyledExpansionPanelSummary.jsx
- src/components/pages/Mages/MageCard.jsx
- src/components/pages/Mages/MageList.jsx
- src/components/pages/Mages/mageStyles.jsx
- src/components/pages/Nemeses/index.jsx
- src/components/pages/Nemeses/nemesesStyles.js
- src/components/pages/Settings/index.jsx
- src/components/pages/Settings/settingStyles.js
- src/components/pages/Supply/index.jsx
- src/components/pages/Supply/supplyStyles.js
- src/components/pages/TurnOrder/TurnOrderSetup.jsx
- src/components/pages/TurnOrder/TurnOrderTable.jsx
- src/components/pages/TurnOrder/TurnOrderTableCell.jsx
- src/components/pages/TurnOrder/TurnOrderTableRow.jsx
- src/components/pages/TurnOrder/turnOrderStyles.js
- src/config/turnOrderSetups.js
> [FEATURE] Improve styling and add turn order highlights

- package-lock.json
- package.json
- src/components/pages/Supply/hooks.js
- src/components/pages/Supply/index.jsx
> [BUGFIX] Clear supply on market setup change

- package-lock.json
- package.json
- src/components/App/index.jsx
- src/components/pages/Settings/ActiveSets.jsx
- src/components/pages/Settings/index.jsx
- src/components/pages/Supply/MarketTile.jsx
- src/config/aeonsData.js
- src/hooks/useSelectedSets.jsx
> [FEATURE] Add promos, split sets by type and sort

- .circleci/config.yml
- README.md
> [TASK]: Add circleCI config

- src/components/App/appStyles.ts
- src/components/App/index.tsx
- src/components/Content.tsx
> [FEATURE]: Add loading spinner

- src/components/pages/TurnOrder/ActiveTurnOrder.tsx
> [TASK] Optimize draw button size for turn order

- src/components/pages/TurnOrder/TurnOrderSetupSelection.tsx
- src/components/pages/TurnOrder/hooks.ts
- src/components/pages/TurnOrder/index.tsx
- src/components/pages/TurnOrder/turnOrderStyles.ts
- src/config/turnOrderSetups.ts
- src/config/types.ts
> [FEATURE]: Add Maelstrom-Card to turnorder setups

- src/config/aeonsData.ts
> [TASK] Rename legacy mages to identify them

- src/components/App/UpdateScreen.tsx
> [BUGFIX] Fix update screen

- src/components/pages/Mages/mageStyles.tsx
- src/components/pages/Supply/supplyStyles.ts
> [BUGFIX] Fix tile height of mages and supply

- CONTRIBUTING.md
- README.md
> [TASK] Add contribution guidelines

- src/components/pages/Supply/MarketOptions.tsx
- src/components/pages/Supply/MarketOptionsWrapper.tsx
- src/components/pages/Supply/MarketTile.tsx
- src/components/pages/Supply/PreviewTile.tsx
- src/components/pages/Supply/PreviewTileList.tsx
- src/components/pages/Supply/PreviewTileListItem.tsx
- src/components/pages/Supply/helpers.ts
- src/components/pages/Supply/index.tsx
- src/components/pages/Supply/supplyStyles.ts
> [FEATURE] Add market setup preview

- CONTRIBUTING.md
- src/Redux/Store/Mages/index.ts
- src/Redux/Store/Settings/Expansions/index.ts
- src/Redux/Store/Settings/SupplySetups/index.ts
- src/Redux/Store/Settings/index.ts
- src/Redux/Store/Supply/RandomSetup/index.ts
- src/Redux/Store/Supply/index.ts
- src/Redux/Store/TurnOrder/index.ts
- src/Redux/Store/index.ts
- src/components/App/MainApp.tsx
- src/components/SupplyPreview/index.tsx
- src/components/pages/Mages/index.tsx
- src/components/pages/Nemeses/index.tsx
- src/components/pages/Settings/Expansions/ActiveSets.tsx
- src/components/pages/Settings/Supply/CheckboxWithPreview.tsx
- src/components/pages/Settings/Supply/SetupSelection.tsx
- src/components/pages/Supply/MarketOptions.tsx
- src/components/pages/Supply/index.tsx
- src/components/pages/TurnOrder/ActiveGame.tsx
- src/components/pages/TurnOrder/DiscardTable.tsx
- src/components/pages/TurnOrder/ModeSelection.tsx
- src/components/pages/TurnOrder/PlayerCountSelection.tsx
- src/components/pages/TurnOrder/SetupSelection.tsx
- src/components/pages/TurnOrder/TableRow.tsx
- src/components/pages/TurnOrder/TurnOrderConfiguration.tsx
- src/components/pages/TurnOrder/index.tsx
> [FEATURE] Load supply setups on startup (+ some refactoring) 

- .gitattributes
> [TASK]: Update .gitattributes for images

- src/components/NoSelectedExpansions.tsx
> [FEATURE]: Add link to settings if no standalone exp selected

- src/components/pages/Expeditions/Expedition/BattleLost.tsx
> [BUGFIX] Fix battle lost in big pocket mode

- src/components/pages/Settings/Supply/CustomSetupEdit/BluePrint.tsx
- src/components/pages/Settings/Supply/CustomSetupEdit/BluePrintWrapper.tsx
> [TASK] Set color according to card type in custom setup

- src/Redux/Store/TurnOrder/Configuration/index.ts
- src/types/turnOrder.ts
> FEATURE: Add blitz + maelstrom mode to turnorder deck

- src/Redux/Store/TurnOrder/ActiveGame/__test__/reducer.test.ts
- src/Redux/Store/TurnOrder/ActiveGame/__test__/selectors.test.ts
- src/Redux/Store/TurnOrder/ActiveGame/reducer.ts
- src/Redux/Store/TurnOrder/ActiveGame/reducerHelpers/newRound.ts
- src/Redux/Store/TurnOrder/ActiveGame/reducerHelpers/resetGame.ts
- src/Redux/Store/TurnOrder/ActiveGame/reducerHelpers/startGame.ts
- src/Redux/Store/TurnOrder/ActiveGame/selectors.ts
- src/Redux/Store/TurnOrder/ActiveGame/types.ts
- src/components/pages/TurnOrder/ActiveGame.tsx
- src/components/pages/TurnOrder/RoundCount/Wrapper.tsx
- src/components/pages/TurnOrder/RoundCount/index.tsx
> FEATURE: Add turnorder round counter

- docs/CustomExpeditions/README.md
- src/components/pages/About/index.tsx
- src/components/pages/Expeditions/CreationDialog/ConfigImport/expeditionJsonSchema.ts
> Further narrative expedition enhancements

- docs/CustomExpeditions/Types.md
- src/Redux/Store/Expeditions/Expeditions/sideEffects/createBattle/__test__/createBattle.test.ts
- src/Redux/Store/Expeditions/Expeditions/sideEffects/createBattle/index.ts
> FEATURE: Add nemesisId to battle.config

- README.md
- docs/CustomExpeditions/Example.md
- docs/CustomExpeditions/Types.md
- package.json
- src/Redux/Store/Expeditions/Expeditions/__test__/reducer.test.ts
- src/Redux/Store/Expeditions/Expeditions/reducerHelpers/rollLoss.ts
- src/Redux/Store/Expeditions/Expeditions/sideEffects/createRewards/index.ts
- src/Redux/Store/Expeditions/Expeditions/sideEffects/helpers.ts
- src/Redux/Store/Expeditions/Expeditions/sideEffects/rollLossRewards/index.ts
- src/components/pages/Expeditions/Expedition/Branch/Battle/BattleLost/LossRewardTypeSelection/ConfirmButton.tsx
- src/components/pages/Expeditions/Expedition/Branch/Battle/BattleLost/LossRewardTypeSelection/index.tsx
> Custom loss rewards

- package.json
- src/components/molecules/MarketTile/Body.tsx
- src/components/molecules/MarketTile/index.tsx
- src/components/molecules/SupplyList/index.tsx
- src/components/pages/Expeditions/CreationDialog/ConfigImport/expeditionJsonSchema.ts
- src/components/pages/Expeditions/CreationDialog/index.tsx
- yarn.lock
> 364 fix expedition import

- src/components/pages/About/index.tsx
> TASK: Add additional infos to about page

- README.md
> Task: Update README

- src/Redux/Store/TurnOrder/Configuration/__test__/helpers.test.ts
- src/Redux/Store/TurnOrder/Configuration/helpers.ts
- src/aer-data/src/turnOrderSetups.ts
- src/aer-types/types/turnOrder.ts
- src/mainTheme.ts
> FEATURE: Add thief of dreams toc

- docs/CustomExpeditions/API.md
- docs/CustomExpeditions/Types.md
- expeditions/intoTheWild.json
- expeditions/newAge.json
- src/Redux/Store/Expeditions/Expeditions/helpers/__test__/convertExpeditionFromConfig.test.ts
- src/Redux/Store/Expeditions/Expeditions/helpers/convertExpeditionFromConfig.ts
- src/Redux/Store/Expeditions/Expeditions/sideEffects/createExpeditionConfig/handleExistingConfig.ts
- src/Redux/Store/Expeditions/Expeditions/sideEffects/createSettingsSnapshot/__test__/createSettingsSnapshot.test.ts
- src/Redux/Store/Expeditions/Expeditions/sideEffects/createSettingsSnapshot/__test__/handleExistingSettingsSnapshot.test.ts
- src/Redux/Store/Expeditions/Expeditions/sideEffects/createSettingsSnapshot/determineUsedExpansions.ts
- src/Redux/Store/Expeditions/Expeditions/sideEffects/createSettingsSnapshot/handleExistingSettingsSnapshot.ts
- src/Redux/Store/Expeditions/Expeditions/sideEffects/createSettingsSnapshot/index.ts
- src/Redux/Store/Expeditions/Expeditions/sideEffects/rollLossRewards/index.ts
- src/Redux/Store/Expeditions/Expeditions/sideEffects/rollWinRewards/index.ts
- src/Redux/Store/Expeditions/Expeditions/types.ts
- src/aer-types/types/expeditions.ts
- src/components/pages/About/index.tsx
- src/components/pages/Expeditions/CreationDialog/ConfigImport/expeditionJsonSchema.ts
- src/components/pages/Expeditions/CreationDialog/index.tsx
- src/components/pages/Expeditions/Expedition/Branch/Battle/BattleLost/LossRewardTypeSelection/index.tsx
- src/components/pages/Expeditions/Expedition/Branch/Battle/BattleLost/index.tsx
- src/components/pages/Expeditions/Expedition/Branch/Battle/BattleWon/index.tsx
- src/components/pages/TurnOrder/ModeSelection.tsx
> Add expedition DSL features

- src/aer-data/src/PL/aeonsEnd/cards.ts
<details>
<summary>Card image from the game</summary>
</details>
> Update BurningOpal in Polish

- README.md
- docker/Dockerfile
- docker/docker-compose.yml
- docker/nginx.conf
Fixes: #450
Added a docker-compose setup to deploy the production build inside docker.
> [FEATURE] Added docker-compose setup

- src/Redux/Store/Settings/Expansions/Nemeses/selected/__test__/__snapshots__/reducer.test.ts.snap
- src/aer-data/src/ENG/community/cards.ts
- src/aer-data/src/ENG/community/index.ts
- src/aer-data/src/ENG/community/mages.ts
- src/aer-data/src/ENG/community/nemeses.ts
- src/aer-data/src/ENG/index.ts
Issue: #451
Added community expansion with the nemesis Haze Fiend from Legacy
The community was added to the "promo" tab. Not sure if we should make another tab just for community stuff?
> [FEATURE] Community Additions: Haze Fiend

- src/aer-data/src/PL/index.ts
- src/aer-data/src/PL/legacy/basicNemesisCards.ts
- src/aer-data/src/PL/legacy/cards.ts
- src/aer-data/src/PL/legacy/index.ts
- src/aer-data/src/PL/legacy/mages.ts
- src/aer-data/src/PL/legacy/nemeses.ts
- src/aer-data/src/PL/promos/cards.ts
Adding polish translation of wave 3 Aeon's End (Legacy) + Legacy promos
> polish translations

- src/aer-data/src/FR/aeonsEnd/basicNemesisCards.ts
Adding french translations to AE core basic nemesis cards
> French translation - AE core basic nemesis cards

- .gitignore
- src/aer-data/.gitignore
- src/aer-data/src/ENG/legacyOfGravehold/upgradedBasicNemesisCards.ts
> FIX: Stifle nemesis card tier

- src/components/pages/Settings/Language/GameLanguageSelection/GameLanguageSelection.tsx
- src/components/pages/Settings/Language/index.tsx
- src/components/pages/Settings/index.tsx
I've added a small tooltip within the settings menu with a tooltip text to guide users as how to change the game language.
I didn't write any test as I don't know how to, I tried to respect your architecture as much as I could, feel free to correct any mistakes I could have made.
> Language selection expansion panel tooltip

- src/components/molecules/MarketTile/index.tsx
- src/components/molecules/SupplyList/index.tsx
- src/components/pages/Expeditions/Expedition/Barracks/Banished.tsx
- src/components/pages/Expeditions/Expedition/Barracks/Supply.tsx
- src/components/pages/Expeditions/Expedition/Branch/SupplyReward.tsx
- src/components/pages/Randomizer/Supply/index.tsx
> 367 remove lock icon in expeditions

- src/Redux/Store/Settings/Expansions/GlobalLanguage/__test__/reducer.test.ts
- src/Redux/Store/Settings/Expansions/GlobalLanguage/__test__/selectors.test.ts
- src/Redux/Store/Settings/Expansions/GlobalLanguage/actions.ts
- src/Redux/Store/Settings/Expansions/GlobalLanguage/constants.ts
- src/Redux/Store/Settings/Expansions/GlobalLanguage/index.ts
- src/Redux/Store/Settings/Expansions/GlobalLanguage/reducer.ts
- src/Redux/Store/Settings/Expansions/GlobalLanguage/reducerHelpers/fetchFromDb.ts
- src/Redux/Store/Settings/Expansions/GlobalLanguage/reducerHelpers/index.ts
- src/Redux/Store/Settings/Expansions/GlobalLanguage/reducerHelpers/select.ts
- src/Redux/Store/Settings/Expansions/GlobalLanguage/selectors.ts
- src/Redux/Store/Settings/Expansions/GlobalLanguage/types.ts
- src/Redux/Store/Settings/Expansions/index.ts
- src/Redux/Store/Settings/Expansions/types.ts
- src/components/pages/Settings/Expansions/ActiveSets/Wrapper.tsx
- src/components/pages/Settings/Expansions/ActiveSets/index.tsx
- src/components/pages/Settings/Expansions/ContentCustomization/index.tsx
> FEATURE: Change expansion language globally

- src/aer-data/src/ENG/returnToGravehold/mages.ts
- src/aer-types/types/data.ts
- src/components/molecules/MageInformation/index.tsx
Adds `numberOfOvercharges` field to store the optional charges. Seems to be the last item from #383.
> FEATURE: Format Cairna's charges as "3 + 3"

- src/Redux/Store/Expeditions/Expeditions/__test__/reducer.test.ts
- src/Redux/Store/Expeditions/Expeditions/reducerHelpers/createExpedition.ts
- src/Redux/Store/Snackbars/__test__/reducer.test.ts
- src/Redux/Store/Snackbars/__test__/selectors.test.ts
- src/Redux/Store/Snackbars/actions.ts
- src/Redux/Store/Snackbars/index.ts
- src/Redux/Store/Snackbars/reducer.ts
- src/Redux/Store/Snackbars/selectors.ts
- src/Redux/Store/Snackbars/types.ts
- src/Redux/Store/index.ts
- src/components/App/MainApp.tsx
- src/components/molecules/Snackbars/Snackbar.tsx
- src/components/molecules/Snackbars/__styled__/CloseButton.tsx
- src/components/molecules/Snackbars/__styled__/Content.tsx
- src/components/molecules/Snackbars/__styled__/Wrapper.tsx
- src/components/molecules/Snackbars/index.tsx
- src/mainTheme.ts
Closes #317
I included one example snackbar for successfully creating an expedition. I think, we could then add snackbars as an ongoing process when we need one somewhere.
> FEATURE: Add snackbars

- src/aer-data/src/PL/buriedSecrets/basicNemesisCards.ts
- src/aer-data/src/PL/buriedSecrets/cards.ts
- src/aer-data/src/PL/buriedSecrets/index.ts
- src/aer-data/src/PL/buriedSecrets/mages.ts
- src/aer-data/src/PL/buriedSecrets/nemeses.ts
- src/aer-data/src/PL/promos/cards.ts
Added translation to Burried Secrets expansion + 2 promos.
> Pltranslations

- src/aer-data/src/PL/index.ts
Added missing import to index.ts for Burried Secrets
> Import to buried secrets added to index file

- src/aer-data/src/PL/index.ts
- src/aer-data/src/PL/intoTheWild/cards.ts
- src/aer-data/src/PL/intoTheWild/index.ts
- src/aer-data/src/PL/intoTheWild/mages.ts
- src/aer-data/src/PL/intoTheWild/nemeses.ts
- src/aer-data/src/PL/intoTheWild/treasures.ts
- src/aer-data/src/PL/theNewAge/basicNemesisCards.ts
- src/aer-data/src/PL/theNewAge/cards.ts
- src/aer-data/src/PL/theNewAge/index.ts
- src/aer-data/src/PL/theNewAge/mages.ts
- src/aer-data/src/PL/theNewAge/nemeses.ts
- src/aer-data/src/PL/theNewAge/treasures.ts
- src/aer-data/src/PL/theNewAge/upgradedBasicNemesisCards.ts
Polish translation for The New Age & Into the Wild
> The new age&into the wild translation

- src/aer-data/src/PL/outerDark/cards.ts
- src/aer-data/src/PL/theVoid/cards.ts
> PolishTranslationFix

- src/aer-data/src/DE/promos/cards.ts
German translation of promo card Echo Stone
> [FEATURE] german translation promo wave 3

- src/Redux/Store/Settings/Expansions/Cards/index.ts
- src/Redux/Store/Settings/Expansions/Cards/selected/actions.ts
- src/Redux/Store/Settings/Expansions/Cards/selected/reducer.ts
- src/Redux/Store/Settings/Expansions/Cards/selected/reducerHelpers/deselectCards.ts
- src/Redux/Store/Settings/Expansions/Cards/selected/reducerHelpers/index.ts
- src/Redux/Store/Settings/Expansions/Cards/selected/types.ts
- src/components/molecules/ListWrapper/index.tsx
- src/components/pages/Settings/Expansions/ActiveSets/DeselectByKeyword/KeywordButton.tsx
- src/components/pages/Settings/Expansions/ActiveSets/DeselectByKeyword/helpers.ts
- src/components/pages/Settings/Expansions/ActiveSets/DeselectByKeyword/index.tsx
- src/components/pages/Settings/Expansions/ActiveSets/index.tsx
Fixes #502
(Once more with feeling. Usually force-push doesn't close the PR, unless that's a per-repo setting.)
> FEATURE: Buttons to deselect cards by keyword

- src/aer-data/src/DE/buriedSecrets/basicNemesisCards.ts
- src/aer-data/src/DE/buriedSecrets/cards.ts
- src/aer-data/src/DE/buriedSecrets/index.ts
- src/aer-data/src/DE/buriedSecrets/mages.ts
- src/aer-data/src/DE/buriedSecrets/nemeses.ts
- src/aer-data/src/DE/index.ts
German translation of expansion W3-E1
> [FEATURE] german translation expansion wave 3

- src/aer-data/src/PL/index.ts
- src/aer-data/src/PL/theAncients/cards.ts
- src/aer-data/src/PL/theAncients/index.ts
- src/aer-data/src/PL/theAncients/mages.ts
- src/aer-data/src/PL/theAncients/nemeses.ts
- src/aer-data/src/PL/theAncients/treasures.ts
- src/aer-data/src/PL/theAncients/upgradedBasicNemesisCards.ts
Translation for the newest dlc in polish language
> The ancients translation

- src/aer-data/src/FR/index.ts
- src/aer-data/src/FR/outerDark/basicNemesisCards.ts
- src/aer-data/src/FR/outerDark/cards.ts
- src/aer-data/src/FR/outerDark/index.ts
- src/aer-data/src/FR/outerDark/mages.ts
- src/aer-data/src/FR/outerDark/nemeses.ts
- src/aer-data/src/FR/theVoid/cards.ts
- src/aer-data/src/FR/theVoid/index.ts
- src/aer-data/src/FR/theVoid/mages.ts
- src/aer-data/src/FR/theVoid/nemeses.ts
French translation for 2 expansions (The Void and Outer Dark)
> French translation of The Void and Outer Dark

- src/aer-data/src/DE/index.ts
- src/aer-data/src/DE/legacy/basicNemesisCards.ts
- src/aer-data/src/DE/legacy/cards.ts
- src/aer-data/src/DE/legacy/index.ts
- src/aer-data/src/DE/legacy/mages.ts
- src/aer-data/src/DE/legacy/nemeses.ts
- src/aer-data/src/DE/promos/cards.ts
German translation of wave 3 - Aeon's End: Legacy
> [FEATURE] german translation legacy (wave 3)

- src/aer-data/src/DE/aeonsEnd/basicNemesisCards.ts
- src/aer-data/src/DE/aeonsEnd/cards.ts
- src/aer-data/src/DE/index.ts
- src/aer-data/src/DE/intoTheWild/cards.ts
- src/aer-data/src/DE/intoTheWild/index.ts
- src/aer-data/src/DE/intoTheWild/mages.ts
- src/aer-data/src/DE/intoTheWild/nemeses.ts
- src/aer-data/src/DE/intoTheWild/treasures.ts
- src/aer-data/src/DE/legacy/cards.ts
- src/aer-data/src/DE/outerDark/cards.ts
- src/aer-data/src/DE/promos/treasures.ts
- src/aer-data/src/DE/shatteredDreams/cards.ts
- src/aer-data/src/DE/shatteredDreams/index.ts
- src/aer-data/src/DE/shatteredDreams/mages.ts
- src/aer-data/src/DE/shatteredDreams/nemeses.ts
- src/aer-data/src/DE/shatteredDreams/treasures.ts
- src/aer-data/src/DE/theAncients/cards.ts
- src/aer-data/src/DE/theAncients/index.ts
- src/aer-data/src/DE/theAncients/mages.ts
- src/aer-data/src/DE/theAncients/nemeses.ts
- src/aer-data/src/DE/theAncients/treasures.ts
- src/aer-data/src/DE/theAncients/upgradedBasicNemesisCards.ts
- src/aer-data/src/DE/theDepths/cards.ts
- src/aer-data/src/DE/theNewAge/basicNemesisCards.ts
- src/aer-data/src/DE/theNewAge/cards.ts
- src/aer-data/src/DE/theNewAge/index.ts
- src/aer-data/src/DE/theNewAge/mages.ts
- src/aer-data/src/DE/theNewAge/nemeses.ts
- src/aer-data/src/DE/theNewAge/treasures.ts
- src/aer-data/src/DE/theNewAge/upgradedBasicNemesisCards.ts
- complete german translation of wave 4 (base game, 3 mini expansions, promo pack)
- errata from update pack for waves 1-3
- minor translation fixes
> [FEATURE] german translation the new age (wave 4)

- src/aer-data/src/ENG/origins/cards.ts
https://aeonsend.fandom.com/wiki/Rhodonix
> [Fix] Rhodonix costs 6, not 3.

- src/components/molecules/AmountPicker.tsx
Eliminates a stack trace in the developer tools.
> [Fix] Set key on radio buttons in mage randomizer

- cypress/e2e/Expeditions/creationAndRunThrough.cy.ts
- cypress/e2e/Expeditions/seeds.cy.ts
- src/Redux/Store/Settings/Expansions/Cards/selected/__test__/__snapshots__/reducer.test.ts.snap
- src/aer-data/src/ENG/pastAndFuture/cards.ts
> Deusabianca resonantpearl
